name: Manual Publish to PyPI

on:
  workflow_dispatch:  # 手动触发
    inputs:
      version:
        description: "Stable version (e.g., 1.0.0)"
        required: true
        type: string

jobs:
  build-and-publish-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Change directory to python
        run: cd python

      - name: Remove existing dist folder
        run: |
          if [ -d "dist" ]; then
            rm -rf dist/
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          # 使用用户指定的版本号
          echo "PACKAGE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
