name: Python Tests

on:
  pull_request:
    branches: [ main, v0.3.0_dev, v0.4.0_dev ]
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史用于SonarQube分析

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black bandit safety

    - name: Lint Python code
      working-directory: ./python
      run: |
        flake8 agentbay tests examples
        black --check agentbay tests examples

    - name: Security scan with Bandit
      working-directory: ./python
      run: |
        bandit -r agentbay -f json -o bandit-results.json

    - name: Check dependencies for vulnerabilities
      working-directory: ./python
      run: |
        poetry export -f requirements.txt -o requirements.txt --without-hashes
        safety check -r requirements.txt || true

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ./python
        args: >
          -Dsonar.projectKey=wuying-agentbay-sdk_python
          -Dsonar.organization=wuying-agentbay
          -Dsonar.python.coverage.reportPaths=coverage.xml

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry add --dev pytest-cov

    - name: Run unit tests with coverage
      working-directory: ./python
      run: |
        poetry run python -m pytest tests/unit -v --cov=agentbay --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./python/coverage.xml
        flags: python
        name: python-${{ matrix.python-version }}
        fail_ci_if_error: false

    # - name: Run integration tests (if API key is provided)
    #   working-directory: ./python
    #   if: ${{ secrets.AGENTBAY_API_KEY != '' }}
    #   env:
    #     AGENTBAY_API_KEY: ${{ secrets.AGENTBAY_API_KEY }}
    #   run: |
    #     poetry run python -m pytest tests/integration -v

  quality-gate:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check Codecov coverage threshold
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "70"
          filename: "./python/coverage.xml"
          clover: true
          log-level: error